name: customers
port: 8081
openapi:
  title: Mi API
  version: 1.0.0
  openapi_version: 3.1.0
  summary: API de ejemplo
  description: Documentación de la API con configuración avanzada
  tags:  
    users:
      prefix: /users
      description: Operaciones relacionadas con usuarios
    payments:
      prefix: /payments
      description: Gestión de pagos
    customers:
      prefix: /customers
      description: Gestión de clientes
  servers:
    - url: http://localhost:8081
      description: Servidor de desarrollo
    - url: https://api.miapp.com
      description: Servidor principal de producción
    - url: https://staging.miapp.com
      description: Servidor de pruebas
  terms_of_service: https://miapp.com/terms
  contact:
    name: Soporte Técnico
    url: https://miapp.com/support
    email: support@miapp.com
  license_info:
    name: MIT
    url: https://opensource.org/licenses/MIT
  separate_input_output_schemas: true
features: customers.features



middlewares:  
  - class: CORSMiddleware
    options:
      allow_origins: ["*"]
      #allow_methods: ["*"]
      allow_headers: ["Authorization"]
      #allow_credentials: true
      #expose_headers: ["X-Total-Count"]
      max_age: 3600  
  - class: AuthMiddleware
  - class: ErrorMiddleware


development:
  debug: true
  reload: true
  log_level: debug
  firestore:
    database: (default)
    credentials_env: GOOGLE_APPLICATION_CREDENTIALS

production:
  debug: false
  reload: false
  log_level: info
  firestore:
    database: (default)
    credentials_env: GOOGLE_APPLICATION_CREDENTIALS
